name: Test, Build Features

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements.txt
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest flake8
      - name: Run linting
        run: | 
          flake8
      - name: Run pytest Unit tests
        run: |
          pytest
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: my/music-api:latest
